language: php
php:
  - '7.2'
install: composer install
script:
  - mkdir -p $TRAVIS_BUILD_DIR/build/logs
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit
  - $TRAVIS_BUILD_DIR/vendor/bin/php-cs-fixer fix --dry-run --allow-risky=yes
  - travis_retry php vendor/bin/php-coveralls